name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wp-php
      - mariadb
    networks:
      - my_network
    volumes:
      - wp-volume:/var/www/html

  wp-php:
    container_name: wp-php
    build: ./requirements/wp-php
    image: wp-php
    depends_on:
      - mariadb
    networks:
      - my_network
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    networks:
      - my_network
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  wp-volume:
    name: wp-volume
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind

networks:
  my_network:
    driver: bridge
