name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wp-php
    networks:
      - my_network
    volumes:
      - ./requirements/wordpress:/var/www/html

  wp-php:
    container_name: wp-php
    build: ./requirements/wp-php
    depends_on:
      - mariadb
    networks:
      - my_network
    env_file:
      - .env
    volumes:
      - ./requirements/wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    networks:
      - my_network
    env_file:
      - .env
    volumes:
      - ./requirements/mariadb/database:/var/lib/mysql

networks:
  my_network:
    driver: bridge