name: inception

services:
  nginx:
    container_name: nginx
    build: ./srcs/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php
    build: ./srcs/php
    depends_on:
      - mariadb
    environment:
      - DB_USER=mysql
      - DB_PASSWORD=mysql
      - DB_NAME=my_database
      - DB_HOST=mariadb
      - DB_PORT=3306

  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
      - MYSQL_user=mysql
      - MYSQL_PASSWORD=mysql
      # - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      # - MYSQL_ROOT_HOST='%'
    # volumes:
    #   - ./srcs/mariadb/my_database.sql:/docker-entrypoint-initdb.d/my_database.sql
