name: inception

services: # アプリケーションを構築する各サービス
  nginx:
    build: .
    ports: # コンテナ内のポートをホストに公開する
      - "8080:80" # ホストのポート443をコンテナ内のポート443にマッピングする
    volumes:
      - ./srcs/nginx:/etc/nginx # nginxをコンテナにマウント
      #php-wordpress:
      #images: php # イメージからコンテナを起動するための方法がわからない
    # phpのポート番号がわからない
